set_property SRC_FILE_INFO {cfile:F:/General_Platform/fpga/demo_mcu/src/demo_mcu.xdc rfile:../../../src/demo_mcu.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R4          [get_ports CLK_clk_p]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   T6          [get_ports NRST]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   AB15        [get_ports UART_rxd]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   Y16         [get_ports UART_txd]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   AA16        [get_ports UART_gnd]
