set_property SRC_FILE_INFO {cfile:F:/General_Readout_Platform/gen1/fpga/demo_mcu/src/demo_mcu.xdc rfile:../../../src/demo_mcu.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R4          [get_ports CLK_clk_p]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   T6          [get_ports NRST]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   M16         [get_ports LED[3]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   M15         [get_ports LED[2]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   K16         [get_ports LED[1]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   L16         [get_ports LED[0]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   AB15        [get_ports UART_rxd]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   Y16         [get_ports UART_txd]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   AA16        [get_ports UART_gnd]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   H18         [get_ports I2C_DAC_scl_io]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   H17         [get_ports I2C_DAC_sda_io]
