# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0.xci
# IP: The module: 'bd_mcu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0.xci
# IP: The module: 'bd_mcu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/General_Readout_Platform/gen1/fpga/demo_mcu/demo_mcu.srcs/sources_1/bd/bd_mcu/ip/bd_mcu_axi_gpio_0_0/bd_mcu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mcu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
