set_property SRC_FILE_INFO {cfile:F:/General_Platform/fpga/demo_led/src/demo_led.xdc rfile:../../../src/demo_led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R4          [get_ports clk_p]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   J17         [get_ports but1]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   K17         [get_ports but2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   M16         [get_ports led[3]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   M15         [get_ports led[2]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   K16         [get_ports led[1]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN   L16         [get_ports led[0]]
