# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/General_Platform/fpga/demo_mcu/src/demo_mcu.xdc

# Block Designs: bd/bd_mcu/bd_mcu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu || ORIG_REF_NAME==bd_mcu} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_microblaze_0_0/bd_mcu_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_microblaze_0_0 || ORIG_REF_NAME==bd_mcu_microblaze_0_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_dlmb_v10_0/bd_mcu_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_dlmb_v10_0 || ORIG_REF_NAME==bd_mcu_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_ilmb_v10_0/bd_mcu_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_ilmb_v10_0 || ORIG_REF_NAME==bd_mcu_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_dlmb_bram_if_cntlr_0/bd_mcu_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_mcu_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_ilmb_bram_if_cntlr_0/bd_mcu_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_mcu_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_lmb_bram_0/bd_mcu_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_lmb_bram_0 || ORIG_REF_NAME==bd_mcu_lmb_bram_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_mdm_1_0/bd_mcu_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_mdm_1_0 || ORIG_REF_NAME==bd_mcu_mdm_1_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_clk_wiz_1_0/bd_mcu_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_clk_wiz_1_0 || ORIG_REF_NAME==bd_mcu_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_rst_clk_wiz_1_100M_0/bd_mcu_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_mcu_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_axi_uartlite_0_0/bd_mcu_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_axi_uartlite_0_0 || ORIG_REF_NAME==bd_mcu_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_microblaze_0_axi_periph_0/bd_mcu_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bd_mcu_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_mcu/ip/bd_mcu_xlconstant_0_0/bd_mcu_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_mcu_xlconstant_0_0 || ORIG_REF_NAME==bd_mcu_xlconstant_0_0} -quiet] -quiet

# XDC: bd/bd_mcu/bd_mcu_ooc.xdc
