webtalk_init -webtalk_dir F:\\General_Readout_Platform\\gen1\\fpga\\demo_mcu\\demo_mcu.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-11-11 12:53:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "trin4i7al2ca2a584m2e7k1954" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.040 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1636635181356" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1636635181356"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1636635230226"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1636635230226"
webtalk_transmit -clientid 3238356190 -regid "" -xml F:\\General_Readout_Platform\\gen1\\fpga\\demo_mcu\\demo_mcu.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\General_Readout_Platform\\gen1\\fpga\\demo_mcu\\demo_mcu.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\General_Readout_Platform\\gen1\\fpga\\demo_mcu\\demo_mcu.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
